name: testing

on: push

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  GITHUB_TOKEN: ${{ secrets.BARTENDER_PERSONAL_ACCESS_TOKEN }}

jobs:
  install-circt:
    name: install-circt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CIRCT
        uses: circt/install-circt@v1.1.1
        with:
          version-file: ${{ github.workspace }}/etc/circt.json
  update-circt:
    name: update-circt
    runs-on: ubuntu-latest
    steps:
      - name: Update CIRCT
        uses: circt/update-circt@v1.0.0
        with:
          user: 'bartender'
          email: 'firesimchipyard@gmail.com'
          pr-reviewers: 'abejgonzalez,jerryz123'
          pr-labels: 'changelog:changed'
          #github-token: ''
          #
          #  cancel-prior-workflows:
